export const TRIP_PANEL_LABELS = {
  es: {
    addTitle: "Agregar vuelo",
    flightPlaceholder: "Código (AA900, B6766…)",
    originPlaceholder: "Origen IATA",
    destPlaceholder: "Destino IATA",
    bufferLabel: "Llegar",
    addBtn: "Agregar",
    importBtn: "Importar",
    noFlights: "No hay vuelos todavía. Agregá el primero.",
    bufferOptions: [
      { value: 1,   label: "1h antes" },
      { value: 1.5, label: "1:30h antes" },
      { value: 2,   label: "2h antes" },
      { value: 2.5, label: "2:30h antes" },
      { value: 3,   label: "3h antes" },
    ],
    errInvalidCode:    "Código inválido. Usá: AA900, B6766 o EDV5068",
    errUnknownAirline: "Aerolínea no reconocida. Verificá el código.",
    errUnknownOrigin:  "Aeropuerto de origen no reconocido.",
    errUnknownDest:    "Aeropuerto de destino no reconocido.",
    errSameAirport:    "Origen y destino no pueden ser iguales.",
    errMissingDate:    "Ingresá la fecha del vuelo.",
    sectionAirport:   "Aeropuerto de salida",
    sectionRoute:     "Ruta",
    sectionFlight:    "Mi vuelo",
    sectionForecast:  "Pronóstico en la salida",
    sectionTracking:  "Seguimiento en vivo",
    departs: "Sale:",
    arriveAt: "Llegar al aeropuerto:",
    removeTitle: "Eliminar vuelo",
    seeAllFlightsFrom: (code: string) => `FlightAware · Vuelos de ${code}`,
    seeOtherFlights: (o: string, d: string) => `Vuelos alternativos ${o}→${d}`,
    trackFlight: (num: string) => `Tracking vuelo ${num}`,
    trackLive: "Seguir este vuelo en vivo",
    trackInbound: "Ver avión entrante",
    trackNote: "FlightAware muestra posición, velocidad y estado en tiempo real",
    days: (n: number) => `${n} día${n !== 1 ? "s" : ""}`,
    today: "HOY",
    completed: "Completado",
    internationalNote: "Sin cobertura FAA",
    errDuplicateFlight: (code: string) => `El vuelo ${code} ya existe para esa fecha.`,
    warnCloseTimeTitle: "Poco tiempo entre vuelos",
    warnCloseTime: (code: string, mins: number) =>
      `Hay otro vuelo (${code}) a solo ${mins} min de diferencia. ¿Querés agregarlo igual?`,
    confirmAnyway: "Agregar de todas formas",
    addMoreFlights: "Agregar vuelo",
    accSection: "Alojamiento",
    accAdd: "Agregar alojamiento",
    accNamePlaceholder: "Hotel / Airbnb / nombre del lugar",
    accCheckIn: "Check-in",
    accCheckOut: "Check-out",
    accTime: "Hora",
    accConfCode: "Código de reserva (opcional)",
    accAddress: "Dirección (opcional)",
    accRemove: "Eliminar alojamiento",
    accEdit: "Editar alojamiento",
    accSave: "Guardar",
    accCancel: "Cancelar",
    accNights: (n: number) => n === 0 ? "Mismo día" : `${n} noche${n !== 1 ? "s" : ""}`,
    accErrName: "Ingresá el nombre del alojamiento.",
    accErrDates: "La fecha de check-out debe ser posterior al check-in.",
    accTabAI: "TripCopilot IA",
    accTabManual: "Manual",
    accAIPlaceholder: "Pegá tu confirmación o escribí p.ej. \"Marriott BA del 10 al 13 de Abril, check-in a las 15\"",
    accAILoading: "Leyendo reserva...",
    accAIError: "No pude leer la reserva. Revisá el texto o intentá de nuevo.",
    accAIPhoto: "Foto",
    accAIReview: "TripCopilot leyó tu reserva",
    accAIRetry: "Volver a intentar",
    accCopied: "¡Copiado!",
    duplicateTrip: "Duplicar viaje",
    notifLogTitle: "Notificaciones enviadas",
    notifLogEmpty: "Ninguna notificación enviada todavía.",
    notifLogLoading: "Cargando...",
    notifTypes: {
      morning_briefing:  "Resumen matutino",
      checkin_24h:       "Check-in disponible (24h)",
      preflight_3h:      "Alerta pre-vuelo (3h)",
      flight_cancelled:  "Vuelo cancelado",
      flight_delay_real: "Demora en tiempo real",
    } as Record<string, string>,
    sectionSigmet: "SIGMET activo en ruta",
    sectionGate:    "Puerta / Terminal",
    gateNotAssigned: "Las puertas se asignan 24–48h antes de la salida",
    gateConfirmSoon: "Se confirma normalmente el día anterior · Verificar en el aeropuerto",
    gateLiveDay:    "Las puertas pueden cambiar hasta 30 min antes del embarque",
    gateCheckApp:   "Verificar en app de la aerolínea o panel del aeropuerto",
    gateLiveStatus: "Estado en vivo",
    airlineApp:     "App aerolínea",
    connectionRisk: {
      at_risk: (airport: string, mins: number) =>
        `⚠️ Conexión en riesgo en ${airport}${mins > 0 ? ` (+${mins}min demora)` : ""}`,
      tight: (airport: string, mins: number) =>
        `⏱ Conexión ajustada en ${airport}${mins > 0 ? ` (+${mins}min demora)` : ""}`,
      missed: (airport: string, mins: number) =>
        `🚨 Conexión posiblemente perdida en ${airport}${mins > 0 ? ` (+${mins}min demora)` : ""}`,
    },
  },
  en: {
    addTitle: "Add flight",
    flightPlaceholder: "Code (AA900, B6766…)",
    originPlaceholder: "Origin IATA",
    destPlaceholder: "Dest. IATA",
    bufferLabel: "Arrive",
    addBtn: "Add",
    importBtn: "Import",
    noFlights: "No flights yet. Add the first one.",
    bufferOptions: [
      { value: 1,   label: "1h before" },
      { value: 1.5, label: "1:30h before" },
      { value: 2,   label: "2h before" },
      { value: 2.5, label: "2:30h before" },
      { value: 3,   label: "3h before" },
    ],
    errInvalidCode:    "Invalid code. Use: AA900, B6766 or EDV5068",
    errUnknownAirline: "Airline not recognized. Check the code.",
    errUnknownOrigin:  "Origin airport not recognized.",
    errUnknownDest:    "Destination airport not recognized.",
    errSameAirport:    "Origin and destination can't be the same.",
    errMissingDate:    "Enter the flight date.",
    sectionAirport:   "Departure airport",
    sectionRoute:     "Route",
    sectionFlight:    "My flight",
    sectionForecast:  "Forecast at departure",
    sectionTracking:  "Live tracking",
    departs: "Departs:",
    arriveAt: "Arrive at airport by:",
    removeTitle: "Remove flight",
    seeAllFlightsFrom: (code: string) => `FlightAware · Flights from ${code}`,
    seeOtherFlights: (o: string, d: string) => `Alternative flights ${o}→${d}`,
    trackFlight: (num: string) => `Track flight ${num}`,
    trackLive: "Track this flight live",
    trackInbound: "View inbound aircraft",
    trackNote: "FlightAware shows real-time position, speed, and status",
    days: (n: number) => `${n} day${n !== 1 ? "s" : ""} left`,
    today: "TODAY",
    completed: "Completed",
    internationalNote: "No FAA coverage",
    errDuplicateFlight: (code: string) => `Flight ${code} already exists for that date.`,
    warnCloseTimeTitle: "Short time between flights",
    warnCloseTime: (code: string, mins: number) =>
      `Another flight (${code}) is only ${mins} min apart. Add anyway?`,
    confirmAnyway: "Add anyway",
    addMoreFlights: "Add flight",
    accSection: "Accommodation",
    accAdd: "Add accommodation",
    accNamePlaceholder: "Hotel / Airbnb / place name",
    accCheckIn: "Check-in",
    accCheckOut: "Check-out",
    accTime: "Time",
    accConfCode: "Booking code (optional)",
    accAddress: "Address (optional)",
    accRemove: "Remove accommodation",
    accEdit: "Edit accommodation",
    accSave: "Save",
    accCancel: "Cancel",
    accNights: (n: number) => n === 0 ? "Same day" : `${n} night${n !== 1 ? "s" : ""}`,
    accErrName: "Enter the accommodation name.",
    accErrDates: "Check-out must be after check-in.",
    accTabAI: "TripCopilot AI",
    accTabManual: "Manual",
    accAIPlaceholder: "Paste your confirmation or type e.g. \"Marriott BA April 10-13, check-in at 3pm\"",
    accAILoading: "Reading booking...",
    accAIError: "Couldn't read the booking. Check the text or try again.",
    accAIPhoto: "Photo",
    accAIReview: "TripCopilot read your booking",
    accAIRetry: "Try again",
    accCopied: "Copied!",
    duplicateTrip: "Duplicate trip",
    notifLogTitle: "Notifications sent",
    notifLogEmpty: "No notifications sent yet.",
    notifLogLoading: "Loading...",
    notifTypes: {
      morning_briefing:  "Morning briefing",
      checkin_24h:       "Check-in open (24h)",
      preflight_3h:      "Pre-flight alert (3h)",
      flight_cancelled:  "Flight cancelled",
      flight_delay_real: "Real-time delay",
    } as Record<string, string>,
    sectionSigmet: "SIGMET active on route",
    sectionGate:    "Gate / Terminal",
    gateNotAssigned: "Gates typically assigned 24–48h before departure",
    gateConfirmSoon: "Usually confirmed the day before · Verify at airport",
    gateLiveDay:    "Gates can change up to 30 min before boarding",
    gateCheckApp:   "Check airline app or airport departure board",
    gateLiveStatus: "Live status",
    airlineApp:     "Airline app",
    connectionRisk: {
      at_risk: (airport: string, mins: number) =>
        `⚠️ Connection at risk at ${airport}${mins > 0 ? ` (+${mins}min delay)` : ""}`,
      tight: (airport: string, mins: number) =>
        `⏱ Tight connection at ${airport}${mins > 0 ? ` (+${mins}min delay)` : ""}`,
      missed: (airport: string, mins: number) =>
        `🚨 Connection possibly missed at ${airport}${mins > 0 ? ` (+${mins}min delay)` : ""}`,
    },
  },
};

export type TripPanelLabels = typeof TRIP_PANEL_LABELS["es"];

export const AIRLINE_APP_URLS: Record<string, string> = {
  AA: "https://www.aa.com/travelInformation/flights/status",
  UA: "https://www.united.com/ual/en/us/flight-status",
  DL: "https://www.delta.com/us/en/flight-status/overview",
  B6: "https://www.jetblue.com/manage-trips/flightstatus",
  WN: "https://www.southwest.com/air/flight-status/",
  AS: "https://www.alaskaair.com/flight-status",
  LA: "https://www.latamairlines.com/us/en/manage-your-trip",
  AR: "https://www.aerolineas.com.ar/es-ar/informacion-de-vuelo",
  NK: "https://www.spirit.com/booking/flight-status",
  F9: "https://www.flyfrontier.com/travel/my-trips/flight-status/",
  G4: "https://www.allegiantair.com/manage-travel",
  AM: "https://www.aeromexico.com/en-us/flight-status",
  CM: "https://www.copaair.com/en/web/us/check-in",
  AV: "https://www.avianca.com/us/en/manage-your-trip/flight-status/",
  AC: "https://www.aircanada.com/us/en/aco/home/fly/onboard/flight-status.html",
};

export const AIRLINE_CHECKIN_URLS: Record<string, string> = {
  AA: "https://www.aa.com/reservation/retrieveReservationSummaryPage.do",
  UA: "https://www.united.com/ual/en/us/checkin",
  DL: "https://www.delta.com/us/en/check-in/overview",
  B6: "https://www.jetblue.com/manage-trips/check-in",
  WN: "https://www.southwest.com/air/check-in/",
  AS: "https://www.alaskaair.com/check-in",
  LA: "https://www.latamairlines.com/us/en/manage-your-trip/online-check-in",
  AR: "https://www.aerolineas.com.ar/es-ar/online-check-in",
  NK: "https://www.spirit.com/booking/check-in",
  F9: "https://www.flyfrontier.com/travel/my-trips/check-in/",
  G4: "https://www.allegiantair.com/manage-travel",
  AM: "https://www.aeromexico.com/en-us/check-in",
  CM: "https://www.copaair.com/en/web/us/check-in",
  AV: "https://www.avianca.com/us/en/manage-your-trip/check-in/",
  AC: "https://www.aircanada.com/us/en/aco/home/fly/before-you-fly/check-in.html",
};
