export const TRIP_PANEL_LABELS = {
  es: {
    addTitle: "Agregar vuelo",
    flightPlaceholder: "Código (AA900, B6766…)",
    originPlaceholder: "Origen IATA",
    destPlaceholder: "Destino IATA",
    bufferLabel: "Llegar",
    addBtn: "Agregar",
    importBtn: "Importar",
    noFlights: "No hay vuelos todavía. Agregá el primero.",
    bufferOptions: [
      { value: 1,   label: "1h antes" },
      { value: 1.5, label: "1:30h antes" },
      { value: 2,   label: "2h antes" },
      { value: 2.5, label: "2:30h antes" },
      { value: 3,   label: "3h antes" },
    ],
    errInvalidCode:    "Código inválido. Usá: AA900, B6766 o EDV5068",
    errUnknownAirline: "Aerolínea no reconocida. Verificá el código.",
    errUnknownOrigin:  "Aeropuerto de origen no reconocido.",
    errUnknownDest:    "Aeropuerto de destino no reconocido.",
    errSameAirport:    "Origen y destino no pueden ser iguales.",
    errMissingDate:    "Ingresá la fecha del vuelo.",
    sectionAirport:   "Aeropuerto de salida",
    sectionRoute:     "Ruta",
    sectionFlight:    "Mi vuelo",
    sectionForecast:  "Pronóstico en la salida",
    sectionTracking:  "Seguimiento en vivo",
    departs: "Sale:",
    arriveAt: "Llegar al aeropuerto:",
    removeTitle: "Eliminar vuelo",
    seeAllFlightsFrom: (code: string) => `FlightAware · Vuelos de ${code}`,
    seeOtherFlights: (o: string, d: string) => `Vuelos alternativos ${o}→${d}`,
    trackFlight: (num: string) => `Tracking vuelo ${num}`,
    trackLive: "Seguir este vuelo en vivo",
    trackInbound: "Ver avión entrante",
    trackNote: "FlightAware muestra posición, velocidad y estado en tiempo real",
    days: (n: number) => `${n} día${n !== 1 ? "s" : ""}`,
    today: "HOY",
    completed: "Completado",
    internationalNote: "Sin cobertura FAA",
    errDuplicateFlight: (code: string) => `El vuelo ${code} ya existe para esa fecha.`,
    warnCloseTimeTitle: "Poco tiempo entre vuelos",
    warnCloseTime: (code: string, mins: number) =>
      `Hay otro vuelo (${code}) a solo ${mins} min de diferencia. ¿Querés agregarlo igual?`,
    confirmAnyway: "Agregar de todas formas",
    addMoreFlights: "Agregar vuelo",
    accSection: "Alojamiento",
    accAdd: "Agregar alojamiento",
    accNamePlaceholder: "Hotel / Airbnb / nombre del lugar",
    accCheckIn: "Check-in",
    accCheckOut: "Check-out",
    accTime: "Hora",
    accConfCode: "Código de reserva (opcional)",
    accAddress: "Dirección (opcional)",
    accRemove: "Eliminar alojamiento",
    accEdit: "Editar alojamiento",
    accSave: "Guardar",
    accCancel: "Cancelar",
    accNights: (n: number) => n === 0 ? "Mismo día" : `${n} noche${n !== 1 ? "s" : ""}`,
    accErrName: "Ingresá el nombre del alojamiento.",
    accErrDates: "La fecha de check-out debe ser posterior al check-in.",
    accTabAI: "TripCopilot IA",
    accTabManual: "Manual",
    accAIPlaceholder: "Pegá tu confirmación o escribí p.ej. \"Marriott BA del 10 al 13 de Abril, check-in a las 15\"",
    accAILoading: "Leyendo reserva...",
    accAIError: "No pude leer la reserva. Revisá el texto o intentá de nuevo.",
    accAIPhoto: "Foto",
    accAIReview: "TripCopilot leyó tu reserva",
    accAIRetry: "Volver a intentar",
    accCopied: "¡Copiado!",
    duplicateTrip: "Duplicar viaje",
    notifLogTitle: "Notificaciones enviadas",
    notifLogEmpty: "Ninguna notificación enviada todavía.",
    notifLogLoading: "Cargando...",
    notifTypes: {
      morning_briefing:  "Resumen matutino",
      checkin_24h:       "Check-in disponible (24h)",
      preflight_3h:      "Alerta pre-vuelo (3h)",
      flight_cancelled:  "Vuelo cancelado",
      flight_delay_real: "Demora en tiempo real",
    } as Record<string, string>,
    sectionSigmet: "SIGMET activo en ruta",
    sectionGate:    "Puerta / Terminal",
    gateNotAssigned: "Las puertas se asignan 24–48h antes de la salida",
    gateConfirmSoon: "Se confirma normalmente el día anterior · Verificar en el aeropuerto",
    gateLiveDay:    "Las puertas pueden cambiar hasta 30 min antes del embarque",
    gateCheckApp:   "Verificar en app de la aerolínea o panel del aeropuerto",
    gateLiveStatus: "Estado en vivo",
    airlineApp:     "App aerolínea",
    sectionSeat:    "Selección de asiento",
    seatNote:       "Elegí tu asiento directamente en la web de la aerolínea",
    seatAction:     "Seleccionar asiento →",
    connectionRisk: {
      at_risk: (airport: string, mins: number) =>
        `⚠️ Conexión en riesgo en ${airport}${mins > 0 ? ` (+${mins}min demora)` : ""}`,
      tight: (airport: string, mins: number) =>
        `⏱ Conexión ajustada en ${airport}${mins > 0 ? ` (+${mins}min demora)` : ""}`,
      missed: (airport: string, mins: number) =>
        `🚨 Conexión posiblemente perdida en ${airport}${mins > 0 ? ` (+${mins}min demora)` : ""}`,
    },
  },
  en: {
    addTitle: "Add flight",
    flightPlaceholder: "Code (AA900, B6766…)",
    originPlaceholder: "Origin IATA",
    destPlaceholder: "Dest. IATA",
    bufferLabel: "Arrive",
    addBtn: "Add",
    importBtn: "Import",
    noFlights: "No flights yet. Add the first one.",
    bufferOptions: [
      { value: 1,   label: "1h before" },
      { value: 1.5, label: "1:30h before" },
      { value: 2,   label: "2h before" },
      { value: 2.5, label: "2:30h before" },
      { value: 3,   label: "3h before" },
    ],
    errInvalidCode:    "Invalid code. Use: AA900, B6766 or EDV5068",
    errUnknownAirline: "Airline not recognized. Check the code.",
    errUnknownOrigin:  "Origin airport not recognized.",
    errUnknownDest:    "Destination airport not recognized.",
    errSameAirport:    "Origin and destination can't be the same.",
    errMissingDate:    "Enter the flight date.",
    sectionAirport:   "Departure airport",
    sectionRoute:     "Route",
    sectionFlight:    "My flight",
    sectionForecast:  "Forecast at departure",
    sectionTracking:  "Live tracking",
    departs: "Departs:",
    arriveAt: "Arrive at airport by:",
    removeTitle: "Remove flight",
    seeAllFlightsFrom: (code: string) => `FlightAware · Flights from ${code}`,
    seeOtherFlights: (o: string, d: string) => `Alternative flights ${o}→${d}`,
    trackFlight: (num: string) => `Track flight ${num}`,
    trackLive: "Track this flight live",
    trackInbound: "View inbound aircraft",
    trackNote: "FlightAware shows real-time position, speed, and status",
    days: (n: number) => `${n} day${n !== 1 ? "s" : ""} left`,
    today: "TODAY",
    completed: "Completed",
    internationalNote: "No FAA coverage",
    errDuplicateFlight: (code: string) => `Flight ${code} already exists for that date.`,
    warnCloseTimeTitle: "Short time between flights",
    warnCloseTime: (code: string, mins: number) =>
      `Another flight (${code}) is only ${mins} min apart. Add anyway?`,
    confirmAnyway: "Add anyway",
    addMoreFlights: "Add flight",
    accSection: "Accommodation",
    accAdd: "Add accommodation",
    accNamePlaceholder: "Hotel / Airbnb / place name",
    accCheckIn: "Check-in",
    accCheckOut: "Check-out",
    accTime: "Time",
    accConfCode: "Booking code (optional)",
    accAddress: "Address (optional)",
    accRemove: "Remove accommodation",
    accEdit: "Edit accommodation",
    accSave: "Save",
    accCancel: "Cancel",
    accNights: (n: number) => n === 0 ? "Same day" : `${n} night${n !== 1 ? "s" : ""}`,
    accErrName: "Enter the accommodation name.",
    accErrDates: "Check-out must be after check-in.",
    accTabAI: "TripCopilot AI",
    accTabManual: "Manual",
    accAIPlaceholder: "Paste your confirmation or type e.g. \"Marriott BA April 10-13, check-in at 3pm\"",
    accAILoading: "Reading booking...",
    accAIError: "Couldn't read the booking. Check the text or try again.",
    accAIPhoto: "Photo",
    accAIReview: "TripCopilot read your booking",
    accAIRetry: "Try again",
    accCopied: "Copied!",
    duplicateTrip: "Duplicate trip",
    notifLogTitle: "Notifications sent",
    notifLogEmpty: "No notifications sent yet.",
    notifLogLoading: "Loading...",
    notifTypes: {
      morning_briefing:  "Morning briefing",
      checkin_24h:       "Check-in open (24h)",
      preflight_3h:      "Pre-flight alert (3h)",
      flight_cancelled:  "Flight cancelled",
      flight_delay_real: "Real-time delay",
    } as Record<string, string>,
    sectionSigmet: "SIGMET active on route",
    sectionGate:    "Gate / Terminal",
    gateNotAssigned: "Gates typically assigned 24–48h before departure",
    gateConfirmSoon: "Usually confirmed the day before · Verify at airport",
    gateLiveDay:    "Gates can change up to 30 min before boarding",
    gateCheckApp:   "Check airline app or airport departure board",
    gateLiveStatus: "Live status",
    airlineApp:     "Airline app",
    sectionSeat:    "Seat selection",
    seatNote:       "Choose your seat directly on the airline's website",
    seatAction:     "Select seat →",
    connectionRisk: {
      at_risk: (airport: string, mins: number) =>
        `⚠️ Connection at risk at ${airport}${mins > 0 ? ` (+${mins}min delay)` : ""}`,
      tight: (airport: string, mins: number) =>
        `⏱ Tight connection at ${airport}${mins > 0 ? ` (+${mins}min delay)` : ""}`,
      missed: (airport: string, mins: number) =>
        `🚨 Connection possibly missed at ${airport}${mins > 0 ? ` (+${mins}min delay)` : ""}`,
    },
  },
};

export type TripPanelLabels = typeof TRIP_PANEL_LABELS["es"];

export const AIRLINE_APP_URLS: Record<string, string> = {
  AA: "https://www.aa.com/travelInformation/flights/status",
  UA: "https://www.united.com/ual/en/us/flight-status",
  DL: "https://www.delta.com/us/en/flight-status/overview",
  B6: "https://www.jetblue.com/manage-trips/flightstatus",
  WN: "https://www.southwest.com/air/flight-status/",
  AS: "https://www.alaskaair.com/flight-status",
  LA: "https://www.latamairlines.com/us/en/manage-your-trip",
  AR: "https://www.aerolineas.com.ar/es-ar/informacion-de-vuelo",
  NK: "https://www.spirit.com/booking/flight-status",
  F9: "https://www.flyfrontier.com/travel/my-trips/flight-status/",
  G4: "https://www.allegiantair.com/manage-travel",
  AM: "https://www.aeromexico.com/en-us/flight-status",
  CM: "https://www.copaair.com/en/web/us/check-in",
  AV: "https://www.avianca.com/us/en/manage-your-trip/flight-status/",
  AC: "https://www.aircanada.com/us/en/aco/home/fly/onboard/flight-status.html",
  IB: "https://www.iberia.com/us/flight-status/",
  BA: "https://www.britishairways.com/travel/flightstatus/public/en_gb",
  LH: "https://www.lufthansa.com/us/en/flight-status",
  AF: "https://wwws.airfrance.us/information/practical/flight-info",
  KL: "https://www.klm.com/us/en/flight-status",
  EK: "https://www.emirates.com/us/english/manage-booking/flight-status/",
  QR: "https://www.qatarairways.com/en/flight-status.html",
  TK: "https://www.turkishairlines.com/en-us/flights/flight-status/",
  TP: "https://www.flytap.com/en-us/flight-information/flight-status",
  G3: "https://www.voegol.com.br/en/check-in",
  AZ: "https://www.ita-airways.com/en_us/fly-with-us/flight-information.html",
  SK: "https://www.flysas.com/en/travel-info/flight-status/",
  OS: "https://www.austrian.com/us/en/flightinfo",
  LX: "https://www.swiss.com/us/en/prepare/flight-information/flight-status",
  SN: "https://www.brusselsairlines.com/en/flight-status",
  EI: "https://www.aerlingus.com/travel-information/flight-status/",
  VY: "https://www.vueling.com/en/flight-information/flight-status",
  FR: "https://www.ryanair.com/en/flight-status",
  U2: "https://www.easyjet.com/en/flight-status",
  W6: "https://wizzair.com/en-gb/information-and-services/travel-information/flight-status",
  QF: "https://www.qantas.com/us/en/flight-status.html",
  SQ: "https://www.singaporeair.com/en_UK/sg/plan-travel/flight-information/flight-status/",
  CX: "https://www.cathaypacific.com/cx/en_US/fly-with-us/flight-information/flight-status.html",
  NH: "https://www.ana.co.jp/en/us/travel-information/flight-info/",
  JL: "https://www.jal.co.jp/en/inter/flight/",
  ET: "https://www.ethiopianairlines.com/aa/information/flight-status",
  AI: "https://www.airindia.com/in/en/manage/flight-status.html",
  MH: "https://www.malaysiaairlines.com/us/en/plan-and-book/flight-information/flight-status.html",
  TG: "https://www.thaiairways.com/en/flying-with-thai/before-you-fly/flight-status.page",
  OZ: "https://us.flyasiana.com/C/en/us/index.html",
  JJ: "https://www.latamairlines.com/us/en/manage-your-trip",
};

export const AIRLINE_CHECKIN_URLS: Record<string, string> = {
  AA: "https://www.aa.com/homePage.do",
  UA: "https://www.united.com/en/us/checkin",
  DL: "https://www.delta.com/us/en/check-in-security/overview",
  B6: "https://checkin.jetblue.com/",
  WN: "https://www.southwest.com/air/check-in/",
  AS: "https://www.alaskaair.com/checkin",
  LA: "https://www.latamairlines.com/us/en/check-in",
  AR: "https://checkin.aerolineas.com.ar/dx/ARCI/",
  NK: "https://www.spirit.com/home-check-in",
  F9: "https://www.flyfrontier.com/travel/my-trips/check-in/",
  G4: "https://www.allegiantair.com/checkin",
  AM: "https://www.aeromexico.com/en-us/check-in",
  CM: "https://checkin.copaair.com/",
  AV: "https://checkinnew.avianca.com/Check-In?lang=En",
  AC: "https://www.aircanada.com/home/ca/en/aco/checkin",
  IB: "https://www.iberia.com/us/check-in/",
  BA: "https://www.britishairways.com/travel/olcilandingpageauthreq/public/en_gb",
  LH: "https://www.lufthansa.com/us/en/online-check-in",
  AF: "https://wwws.airfrance.us/checkin",
  KL: "https://www.klm.com/us/en/check-in",
  EK: "https://www.emirates.com/us/english/manage-booking/check-in/",
  QR: "https://www.qatarairways.com/en/check-in.html",
  TK: "https://www.turkishairlines.com/en-us/flights/manage-booking/check-in/",
  TP: "https://www.flytap.com/en-us/check-in",
  G3: "https://www.voegol.com.br/en/check-in",
  AZ: "https://www.ita-airways.com/en_us/fly-with-us/check-in.html",
  SK: "https://www.flysas.com/en/travel-info/check-in/",
  OS: "https://www.austrian.com/us/en/check-in",
  LX: "https://www.swiss.com/us/en/prepare/before-the-flight/check-in",
  SN: "https://www.brusselsairlines.com/en/check-in",
  EI: "https://www.aerlingus.com/travel-information/check-in-information/",
  VY: "https://www.vueling.com/en/manage-your-trip/check-in",
  FR: "https://www.ryanair.com/en/check-in",
  U2: "https://www.easyjet.com/en/check-in",
  W6: "https://wizzair.com/en-gb/manage-booking/check-in",
  QF: "https://www.qantas.com/us/en/manage-booking/check-in.html",
  SQ: "https://www.singaporeair.com/en_UK/sg/plan-travel/manage-your-booking/online-check-in/",
  CX: "https://www.cathaypacific.com/cx/en_US/manage-booking/check-in.html",
  NH: "https://www.ana.co.jp/en/us/travel-information/check-in/web-check-in/",
  JL: "https://www.jal.co.jp/en/inter/check_in/",
  ET: "https://www.ethiopianairlines.com/aa/manage/online-check-in",
  AI: "https://www.airindia.com/in/en/manage/check-in.html",
  MH: "https://www.malaysiaairlines.com/us/en/plan-and-book/manage-my-booking.html",
  TG: "https://www.thaiairways.com/en/flying-with-thai/before-you-fly/check-in.page",
  OZ: "https://us.flyasiana.com/C/en/us/index.html",
  JJ: "https://www.latamairlines.com/us/en/check-in",
};

export const AIRLINE_SEAT_URLS: Record<string, string> = {
  AA: "https://www.aa.com/reservation/view/find-your-reservation",
  UA: "https://www.united.com/en/us/manageres/seats",
  DL: "https://www.delta.com/us/en/seat-selection/overview",
  B6: "https://www.jetblue.com/manage-trips/seats",
  AS: "https://www.alaskaair.com/booking/select-seats",
  LA: "https://www.latamairlines.com/us/en/manage-your-trip/choose-seats",
  AR: "https://www.aerolineas.com.ar/es-ar/seleccion-de-asientos",
  NK: "https://www.spirit.com/manage-trips",
  F9: "https://www.flyfrontier.com/travel/my-trips/seat-selection/",
  G4: "https://www.allegiantair.com/manage-travel",
  AM: "https://www.aeromexico.com/en-us/check-in/online/select-seat",
  CM: "https://www.copaair.com/en/web/us/seat-selection",
  AV: "https://www.avianca.com/us/en/manage-your-trip/change-seat/",
  AC: "https://www.aircanada.com/us/en/aco/home/fly/reservations/seat-selection.html",
  IB: "https://www.iberia.com/us/seat-selection/",
  BA: "https://www.britishairways.com/travel/seatselection/execclub/_en_gb",
  LH: "https://www.lufthansa.com/us/en/seat-reservation",
  AF: "https://wwws.airfrance.us/reservation/seat-selection",
  KL: "https://www.klm.com/us/en/reserve-seats",
  EK: "https://www.emirates.com/us/english/manage-booking/seat-selection/",
  QR: "https://www.qatarairways.com/en/seat-selection.html",
  TK: "https://www.turkishairlines.com/en-us/flights/manage-booking/seat-selection/",
  TP: "https://www.flytap.com/en-us/seat-selection",
  AZ: "https://www.ita-airways.com/en_us/fly-with-us/before-departure/seat-choice.html",
  SK: "https://www.flysas.com/en/travel-info/seats/",
  OS: "https://www.austrian.com/us/en/seat-reservation",
  LX: "https://www.swiss.com/us/en/prepare/before-the-flight/select-seat",
  SN: "https://www.brusselsairlines.com/en/seat-reservation",
  SQ: "https://www.singaporeair.com/en_UK/sg/plan-travel/manage-your-booking/change-seat/",
  QF: "https://www.qantas.com/us/en/manage-booking/seat-selection.html",
  CX: "https://www.cathaypacific.com/cx/en_US/manage-booking/change-seat.html",
  NH: "https://www.ana.co.jp/en/us/travel-information/check-in/seat-selection/",
  JL: "https://www.jal.co.jp/en/inter/seat/",
  EI: "https://www.aerlingus.com/travel-information/seats/",
  ET: "https://www.ethiopianairlines.com/aa/manage/seat-selection",
  MH: "https://www.malaysiaairlines.com/us/en/plan-and-book/manage-my-booking.html",
  OZ: "https://us.flyasiana.com/C/en/us/index.html",
};

export const AIRLINE_UPGRADE_URLS: Record<string, string> = {
  AA: "https://www.aa.com/reservation/upgradeReservationFindReservationAccess.do",
  UA: "https://www.united.com/en/us/upgrades",
  DL: "https://www.delta.com/us/en/seat-upgrades/overview",
  B6: "https://www.jetblue.com/upgrade",
  AS: "https://www.alaskaair.com/content/mileage-plan/use-miles/upgrades",
  LA: "https://www.latamairlines.com/us/en/manage-your-trip/upgrade",
  AR: "https://www.aerolineas.com.ar/es-ar/upgrade",
  LH: "https://www.lufthansa.com/us/en/upgrading",
  BA: "https://www.britishairways.com/en-us/information/upgrades",
  EK: "https://www.emirates.com/us/english/before-you-fly/upgrade/",
  QR: "https://www.qatarairways.com/en/privilege-club/upgrade-with-avios.html",
  AF: "https://wwws.airfrance.us/information/practical/upgrade-cabin",
  KL: "https://www.klm.com/us/en/extras/upgrade",
  SQ: "https://www.singaporeair.com/en_UK/sg/plan-travel/your-journey/upgrading/",
  QF: "https://www.qantas.com/us/en/frequent-flyer/points/use-points/upgrade-flights.html",
  TK: "https://www.turkishairlines.com/en-us/flights/upgrades/",
};
