export const AIRPORTS: Record<string, {
  name: string;
  city: string;
  state: string;
  lat: number;
  lng: number;
  icao: string;
  /** Country name — defaults to USA when omitted */
  country?: string;
  /** false = no FAA ASWS coverage (international airports) */
  isFAA?: boolean;
  /** IANA timezone identifier for the airport's local time */
  timezone: string;
}> = {
  ATL: { name: "Hartsfield-Jackson Atlanta",          city: "Atlanta",       state: "GA", lat: 33.6407,  lng: -84.4277,  icao: "KATL", timezone: "America/New_York" },
  LAX: { name: "Los Angeles International",            city: "Los Angeles",   state: "CA", lat: 33.9425,  lng: -118.4081, icao: "KLAX", timezone: "America/Los_Angeles" },
  ORD: { name: "O'Hare International",                 city: "Chicago",       state: "IL", lat: 41.9742,  lng: -87.9073,  icao: "KORD", timezone: "America/Chicago" },
  DFW: { name: "Dallas/Fort Worth International",      city: "Dallas",        state: "TX", lat: 32.8998,  lng: -97.0403,  icao: "KDFW", timezone: "America/Chicago" },
  DEN: { name: "Denver International",                 city: "Denver",        state: "CO", lat: 39.8561,  lng: -104.6737, icao: "KDEN", timezone: "America/Denver" },
  JFK: { name: "John F. Kennedy International",        city: "New York",      state: "NY", lat: 40.6413,  lng: -73.7781,  icao: "KJFK", timezone: "America/New_York" },
  SFO: { name: "San Francisco International",          city: "San Francisco", state: "CA", lat: 37.6213,  lng: -122.3790, icao: "KSFO", timezone: "America/Los_Angeles" },
  SEA: { name: "Seattle-Tacoma International",         city: "Seattle",       state: "WA", lat: 47.4502,  lng: -122.3088, icao: "KSEA", timezone: "America/Los_Angeles" },
  LAS: { name: "Harry Reid International",             city: "Las Vegas",     state: "NV", lat: 36.0840,  lng: -115.1537, icao: "KLAS", timezone: "America/Los_Angeles" },
  MCO: { name: "Orlando International",                city: "Orlando",       state: "FL", lat: 28.4312,  lng: -81.3081,  icao: "KMCO", timezone: "America/New_York" },
  MIA: { name: "Miami International",                  city: "Miami",         state: "FL", lat: 25.7959,  lng: -80.2870,  icao: "KMIA", timezone: "America/New_York" },
  CLT: { name: "Charlotte Douglas International",      city: "Charlotte",     state: "NC", lat: 35.2144,  lng: -80.9473,  icao: "KCLT", timezone: "America/New_York" },
  EWR: { name: "Newark Liberty International",         city: "Newark",        state: "NJ", lat: 40.6895,  lng: -74.1745,  icao: "KEWR", timezone: "America/New_York" },
  PHX: { name: "Phoenix Sky Harbor International",     city: "Phoenix",       state: "AZ", lat: 33.4373,  lng: -112.0078, icao: "KPHX", timezone: "America/Phoenix" },
  IAH: { name: "George Bush Intercontinental",         city: "Houston",       state: "TX", lat: 29.9902,  lng: -95.3368,  icao: "KIAH", timezone: "America/Chicago" },
  BOS: { name: "Logan International",                  city: "Boston",        state: "MA", lat: 42.3656,  lng: -71.0096,  icao: "KBOS", timezone: "America/New_York" },
  MSP: { name: "Minneapolis-Saint Paul International", city: "Minneapolis",   state: "MN", lat: 44.8848,  lng: -93.2223,  icao: "KMSP", timezone: "America/Chicago" },
  DTW: { name: "Detroit Metropolitan Wayne County",    city: "Detroit",       state: "MI", lat: 42.2162,  lng: -83.3554,  icao: "KDTW", timezone: "America/New_York" },
  FLL: { name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", state: "FL", lat: 26.0742, lng: -80.1506, icao: "KFLL", timezone: "America/New_York" },
  LGA: { name: "LaGuardia Airport",                    city: "New York",      state: "NY", lat: 40.7769,  lng: -73.8740,  icao: "KLGA", timezone: "America/New_York" },
  BWI: { name: "Baltimore/Washington International",   city: "Baltimore",     state: "MD", lat: 39.1774,  lng: -76.6684,  icao: "KBWI", timezone: "America/New_York" },
  SLC: { name: "Salt Lake City International",         city: "Salt Lake City",state: "UT", lat: 40.7899,  lng: -111.9791, icao: "KSLC", timezone: "America/Denver" },
  PHL: { name: "Philadelphia International",           city: "Philadelphia",  state: "PA", lat: 39.8744,  lng: -75.2424,  icao: "KPHL", timezone: "America/New_York" },
  DCA: { name: "Ronald Reagan Washington National",    city: "Washington",    state: "DC", lat: 38.8512,  lng: -77.0402,  icao: "KDCA", timezone: "America/New_York" },
  IAD: { name: "Washington Dulles International",      city: "Dulles",        state: "VA", lat: 38.9531,  lng: -77.4565,  icao: "KIAD", timezone: "America/New_York" },
  HNL: { name: "Daniel K. Inouye International",       city: "Honolulu",      state: "HI", lat: 21.3187,  lng: -157.9225, icao: "PHNL", timezone: "Pacific/Honolulu" },
  MDW: { name: "Chicago Midway International",         city: "Chicago",       state: "IL", lat: 41.7868,  lng: -87.7522,  icao: "KMDW", timezone: "America/Chicago" },
  SAN: { name: "San Diego International",              city: "San Diego",     state: "CA", lat: 32.7338,  lng: -117.1933, icao: "KSAN", timezone: "America/Los_Angeles" },
  TPA: { name: "Tampa International",                  city: "Tampa",         state: "FL", lat: 27.9756,  lng: -82.5333,  icao: "KTPA", timezone: "America/New_York" },
  PDX: { name: "Portland International",               city: "Portland",      state: "OR", lat: 45.5898,  lng: -122.5951, icao: "KPDX", timezone: "America/Los_Angeles" },
  EZE: { name: "Ministro Pistarini International",     city: "Buenos Aires",  state: "AR", lat: -34.8222, lng: -58.5358,  icao: "SAEZ", country: "Argentina",  isFAA: false, timezone: "America/Argentina/Buenos_Aires" },
  GCM: { name: "Owen Roberts International",           city: "Grand Cayman",  state: "KY", lat: 19.2928,  lng: -81.3577,  icao: "MWCR", country: "Cayman Islands", isFAA: false, timezone: "America/Cayman" },

  // ── Latin America & Caribbean ─────────────────────────────────────────────
  BOG: { name: "El Dorado International",              city: "Bogotá",        state: "CO", lat:  4.7016,  lng: -74.1469,  icao: "SKBO", country: "Colombia",    isFAA: false, timezone: "America/Bogota" },
  LIM: { name: "Jorge Chávez International",           city: "Lima",          state: "PE", lat: -12.0219, lng: -77.1143,  icao: "SPJC", country: "Peru",        isFAA: false, timezone: "America/Lima" },
  GRU: { name: "São Paulo/Guarulhos International",    city: "São Paulo",     state: "SP", lat: -23.4356, lng: -46.4731,  icao: "SBGR", country: "Brazil",      isFAA: false, timezone: "America/Sao_Paulo" },
  GIG: { name: "Rio de Janeiro/Galeão International",  city: "Rio de Janeiro",state: "RJ", lat: -22.8099, lng: -43.2505,  icao: "SBGL", country: "Brazil",      isFAA: false, timezone: "America/Sao_Paulo" },
  SCL: { name: "Arturo Merino Benítez International",  city: "Santiago",      state: "CL", lat: -33.3930, lng: -70.7858,  icao: "SCEL", country: "Chile",       isFAA: false, timezone: "America/Santiago" },
  MVD: { name: "Carrasco International",               city: "Montevideo",    state: "UY", lat: -34.8383, lng: -56.0308,  icao: "SUMU", country: "Uruguay",     isFAA: false, timezone: "America/Montevideo" },
  PTY: { name: "Tocumen International",                city: "Panama City",   state: "PA", lat:  9.0714,  lng: -79.3835,  icao: "MPTO", country: "Panama",      isFAA: false, timezone: "America/Panama" },
  CUN: { name: "Cancún International",                 city: "Cancún",        state: "QR", lat: 21.0365,  lng: -86.8771,  icao: "MMUN", country: "Mexico",      isFAA: false, timezone: "America/Cancun" },
  MEX: { name: "Benito Juárez International",          city: "Mexico City",   state: "MX", lat: 19.4363,  lng: -99.0721,  icao: "MMMX", country: "Mexico",      isFAA: false, timezone: "America/Mexico_City" },
  NAS: { name: "Lynden Pindling International",        city: "Nassau",        state: "BS", lat: 25.0389,  lng: -77.4662,  icao: "MYNN", country: "Bahamas",     isFAA: false, timezone: "America/Nassau" },
  ANU: { name: "V.C. Bird International",              city: "St. John's",    state: "AG", lat: 17.1367,  lng: -61.7926,  icao: "TAPA", country: "Antigua",     isFAA: false, timezone: "America/Antigua" },
  UIO: { name: "Mariscal Sucre International",         city: "Quito",         state: "EC", lat: -0.1292,  lng: -78.3575,  icao: "SEQM", country: "Ecuador",     isFAA: false, timezone: "America/Guayaquil" },
  VVI: { name: "Viru Viru International",              city: "Santa Cruz",    state: "BO", lat: -17.6448, lng: -63.1354,  icao: "SLVR", country: "Bolivia",     isFAA: false, timezone: "America/La_Paz" },

  // ── More Latin America & Caribbean ───────────────────────────────────────
  BSB: { name: "Presidente Juscelino Kubitschek",     city: "Brasília",      state: "BR", lat: -15.8711, lng: -47.9186,  icao: "SBBR", country: "Brazil",      isFAA: false, timezone: "America/Sao_Paulo" },
  CNF: { name: "Tancredo Neves International",        city: "Belo Horizonte",state: "BR", lat: -19.6244, lng: -43.9719,  icao: "SBCF", country: "Brazil",      isFAA: false, timezone: "America/Sao_Paulo" },
  FOR: { name: "Pinto Martins International",         city: "Fortaleza",     state: "BR", lat: -3.7763,  lng: -38.5326,  icao: "SBFZ", country: "Brazil",      isFAA: false, timezone: "America/Fortaleza" },
  REC: { name: "Guararapes International",            city: "Recife",        state: "BR", lat: -8.1265,  lng: -34.9233,  icao: "SBRF", country: "Brazil",      isFAA: false, timezone: "America/Recife" },
  SSA: { name: "Deputado Luís Eduardo Magalhães",     city: "Salvador",      state: "BR", lat: -12.9086, lng: -38.3225,  icao: "SBSV", country: "Brazil",      isFAA: false, timezone: "America/Bahia" },
  CWB: { name: "Afonso Pena International",           city: "Curitiba",      state: "BR", lat: -25.5285, lng: -49.1758,  icao: "SBCT", country: "Brazil",      isFAA: false, timezone: "America/Sao_Paulo" },
  POA: { name: "Salgado Filho International",         city: "Porto Alegre",  state: "BR", lat: -29.9944, lng: -51.1714,  icao: "SBPA", country: "Brazil",      isFAA: false, timezone: "America/Sao_Paulo" },
  MDE: { name: "José María Córdova International",    city: "Medellín",      state: "CO", lat: 6.1645,   lng: -75.4231,  icao: "SKRG", country: "Colombia",    isFAA: false, timezone: "America/Bogota" },
  CTG: { name: "Rafael Núñez International",          city: "Cartagena",     state: "CO", lat: 10.4424,  lng: -75.5130,  icao: "SKCG", country: "Colombia",    isFAA: false, timezone: "America/Bogota" },
  GYE: { name: "José Joaquín de Olmedo International",city: "Guayaquil",     state: "EC", lat: -2.1574,  lng: -79.8836,  icao: "SEGU", country: "Ecuador",     isFAA: false, timezone: "America/Guayaquil" },
  SDQ: { name: "Las Américas International",          city: "Santo Domingo", state: "DO", lat: 18.4297,  lng: -69.6689,  icao: "MDSD", country: "Dominican Republic", isFAA: false, timezone: "America/Santo_Domingo" },
  SJU: { name: "Luis Muñoz Marín International",      city: "San Juan",      state: "PR", lat: 18.4394,  lng: -66.0018,  icao: "TJSJ", country: "Puerto Rico", isFAA: false, timezone: "America/Puerto_Rico" },
  CUR: { name: "Hato International",                  city: "Willemstad",    state: "CW", lat: 12.1889,  lng: -68.9598,  icao: "TNCC", country: "Curaçao",     isFAA: false, timezone: "America/Curacao" },
  AUA: { name: "Queen Beatrix International",         city: "Oranjestad",    state: "AW", lat: 12.5014,  lng: -70.0152,  icao: "TNCA", country: "Aruba",       isFAA: false, timezone: "America/Aruba" },
  HAV: { name: "José Martí International",            city: "Havana",        state: "CU", lat: 22.9892,  lng: -82.4091,  icao: "MUHA", country: "Cuba",        isFAA: false, timezone: "America/Havana" },
  POS: { name: "Piarco International",                city: "Port of Spain", state: "TT", lat: 10.5954,  lng: -61.3372,  icao: "TTPP", country: "Trinidad & Tobago", isFAA: false, timezone: "America/Port_of_Spain" },
  BGI: { name: "Grantley Adams International",        city: "Bridgetown",    state: "BB", lat: 13.0746,  lng: -59.4925,  icao: "TBPB", country: "Barbados",    isFAA: false, timezone: "America/Barbados" },
  MBJ: { name: "Sangster International",              city: "Montego Bay",   state: "JM", lat: 18.5037,  lng: -77.9134,  icao: "MKJS", country: "Jamaica",     isFAA: false, timezone: "America/Jamaica" },
  KIN: { name: "Norman Manley International",         city: "Kingston",      state: "JM", lat: 17.9357,  lng: -76.7875,  icao: "MKJP", country: "Jamaica",     isFAA: false, timezone: "America/Jamaica" },
  SAL: { name: "Monseñor Óscar Romero International", city: "San Salvador",  state: "SV", lat: 13.4409,  lng: -89.0557,  icao: "MSLP", country: "El Salvador", isFAA: false, timezone: "America/El_Salvador" },
  SJO: { name: "Juan Santamaría International",       city: "San José",      state: "CR", lat: 9.9939,   lng: -84.2088,  icao: "MROC", country: "Costa Rica",  isFAA: false, timezone: "America/Costa_Rica" },
  GUA: { name: "La Aurora International",             city: "Guatemala City",state: "GT", lat: 14.5833,  lng: -90.5275,  icao: "MGGT", country: "Guatemala",   isFAA: false, timezone: "America/Guatemala" },

  // ── Europe ────────────────────────────────────────────────────────────────
  LHR: { name: "Heathrow Airport",                    city: "London",        state: "GB", lat: 51.4775,  lng: -0.4614,   icao: "EGLL", country: "United Kingdom", isFAA: false, timezone: "Europe/London" },
  LGW: { name: "Gatwick Airport",                     city: "London",        state: "GB", lat: 51.1537,  lng: -0.1821,   icao: "EGKK", country: "United Kingdom", isFAA: false, timezone: "Europe/London" },
  STN: { name: "Stansted Airport",                    city: "London",        state: "GB", lat: 51.8850,  lng: 0.2350,    icao: "EGSS", country: "United Kingdom", isFAA: false, timezone: "Europe/London" },
  MAN: { name: "Manchester Airport",                  city: "Manchester",    state: "GB", lat: 53.3537,  lng: -2.2750,   icao: "EGCC", country: "United Kingdom", isFAA: false, timezone: "Europe/London" },
  EDI: { name: "Edinburgh Airport",                   city: "Edinburgh",     state: "GB", lat: 55.9500,  lng: -3.3725,   icao: "EGPH", country: "United Kingdom", isFAA: false, timezone: "Europe/London" },
  CDG: { name: "Charles de Gaulle Airport",           city: "Paris",         state: "FR", lat: 49.0097,  lng: 2.5479,    icao: "LFPG", country: "France",       isFAA: false, timezone: "Europe/Paris" },
  ORY: { name: "Orly Airport",                        city: "Paris",         state: "FR", lat: 48.7233,  lng: 2.3794,    icao: "LFPO", country: "France",       isFAA: false, timezone: "Europe/Paris" },
  AMS: { name: "Amsterdam Airport Schiphol",          city: "Amsterdam",     state: "NL", lat: 52.3086,  lng: 4.7639,    icao: "EHAM", country: "Netherlands",  isFAA: false, timezone: "Europe/Amsterdam" },
  MAD: { name: "Adolfo Suárez Madrid–Barajas",        city: "Madrid",        state: "ES", lat: 40.4839,  lng: -3.5680,   icao: "LEMD", country: "Spain",        isFAA: false, timezone: "Europe/Madrid" },
  BCN: { name: "Josep Tarradellas Barcelona–El Prat", city: "Barcelona",     state: "ES", lat: 41.2971,  lng: 2.0785,    icao: "LEBL", country: "Spain",        isFAA: false, timezone: "Europe/Madrid" },
  FCO: { name: "Leonardo da Vinci–Fiumicino Airport", city: "Rome",          state: "IT", lat: 41.8003,  lng: 12.2389,   icao: "LIRF", country: "Italy",        isFAA: false, timezone: "Europe/Rome" },
  MXP: { name: "Milan Malpensa Airport",              city: "Milan",         state: "IT", lat: 45.6306,  lng: 8.7231,    icao: "LIMC", country: "Italy",        isFAA: false, timezone: "Europe/Rome" },
  MUC: { name: "Munich Airport",                      city: "Munich",        state: "DE", lat: 48.3537,  lng: 11.7750,   icao: "EDDM", country: "Germany",      isFAA: false, timezone: "Europe/Berlin" },
  FRA: { name: "Frankfurt Airport",                   city: "Frankfurt",     state: "DE", lat: 50.0379,  lng: 8.5622,    icao: "EDDF", country: "Germany",      isFAA: false, timezone: "Europe/Berlin" },
  DUS: { name: "Düsseldorf Airport",                  city: "Düsseldorf",    state: "DE", lat: 51.2895,  lng: 6.7668,    icao: "EDDL", country: "Germany",      isFAA: false, timezone: "Europe/Berlin" },
  HAM: { name: "Hamburg Airport",                     city: "Hamburg",       state: "DE", lat: 53.6304,  lng: 9.9882,    icao: "EDDH", country: "Germany",      isFAA: false, timezone: "Europe/Berlin" },
  BER: { name: "Berlin Brandenburg Airport",          city: "Berlin",        state: "DE", lat: 52.3667,  lng: 13.5033,   icao: "EDDB", country: "Germany",      isFAA: false, timezone: "Europe/Berlin" },
  VIE: { name: "Vienna International Airport",        city: "Vienna",        state: "AT", lat: 48.1103,  lng: 16.5697,   icao: "LOWW", country: "Austria",      isFAA: false, timezone: "Europe/Vienna" },
  ZRH: { name: "Zurich Airport",                      city: "Zurich",        state: "CH", lat: 47.4647,  lng: 8.5492,    icao: "LSZH", country: "Switzerland",  isFAA: false, timezone: "Europe/Zurich" },
  GVA: { name: "Geneva Airport",                      city: "Geneva",        state: "CH", lat: 46.2381,  lng: 6.1089,    icao: "LSGG", country: "Switzerland",  isFAA: false, timezone: "Europe/Zurich" },
  BRU: { name: "Brussels Airport",                    city: "Brussels",      state: "BE", lat: 50.9014,  lng: 4.4844,    icao: "EBBR", country: "Belgium",      isFAA: false, timezone: "Europe/Brussels" },
  LIS: { name: "Humberto Delgado Airport",            city: "Lisbon",        state: "PT", lat: 38.7813,  lng: -9.1359,   icao: "LPPT", country: "Portugal",     isFAA: false, timezone: "Europe/Lisbon" },
  OPO: { name: "Francisco Sá Carneiro Airport",       city: "Porto",         state: "PT", lat: 41.2481,  lng: -8.6814,   icao: "LPPR", country: "Portugal",     isFAA: false, timezone: "Europe/Lisbon" },
  CPH: { name: "Copenhagen Airport",                  city: "Copenhagen",    state: "DK", lat: 55.6180,  lng: 12.6560,   icao: "EKCH", country: "Denmark",      isFAA: false, timezone: "Europe/Copenhagen" },
  ARN: { name: "Stockholm Arlanda Airport",           city: "Stockholm",     state: "SE", lat: 59.6519,  lng: 17.9186,   icao: "ESSA", country: "Sweden",       isFAA: false, timezone: "Europe/Stockholm" },
  OSL: { name: "Oslo Gardermoen Airport",             city: "Oslo",          state: "NO", lat: 60.1939,  lng: 11.1004,   icao: "ENGM", country: "Norway",       isFAA: false, timezone: "Europe/Oslo" },
  HEL: { name: "Helsinki-Vantaa Airport",             city: "Helsinki",      state: "FI", lat: 60.3172,  lng: 24.9633,   icao: "EFHK", country: "Finland",      isFAA: false, timezone: "Europe/Helsinki" },
  DUB: { name: "Dublin Airport",                      city: "Dublin",        state: "IE", lat: 53.4213,  lng: -6.2701,   icao: "EIDW", country: "Ireland",      isFAA: false, timezone: "Europe/Dublin" },
  ATH: { name: "Athens International Airport",        city: "Athens",        state: "GR", lat: 37.9364,  lng: 23.9445,   icao: "LGAV", country: "Greece",       isFAA: false, timezone: "Europe/Athens" },
  IST: { name: "Istanbul Airport",                    city: "Istanbul",      state: "TR", lat: 41.2753,  lng: 28.7519,   icao: "LTFM", country: "Turkey",       isFAA: false, timezone: "Europe/Istanbul" },
  SAW: { name: "Sabiha Gökçen International Airport", city: "Istanbul",      state: "TR", lat: 40.8986,  lng: 29.3092,   icao: "LTFJ", country: "Turkey",       isFAA: false, timezone: "Europe/Istanbul" },
  WAW: { name: "Warsaw Chopin Airport",               city: "Warsaw",        state: "PL", lat: 52.1657,  lng: 20.9671,   icao: "EPWA", country: "Poland",       isFAA: false, timezone: "Europe/Warsaw" },
  PRG: { name: "Václav Havel Airport Prague",         city: "Prague",        state: "CZ", lat: 50.1008,  lng: 14.2600,   icao: "LKPR", country: "Czech Republic", isFAA: false, timezone: "Europe/Prague" },
  BUD: { name: "Budapest Ferenc Liszt International", city: "Budapest",      state: "HU", lat: 47.4369,  lng: 19.2556,   icao: "LHBP", country: "Hungary",      isFAA: false, timezone: "Europe/Budapest" },
  OTP: { name: "Henri Coandă International Airport",  city: "Bucharest",     state: "RO", lat: 44.5711,  lng: 26.0850,   icao: "LROP", country: "Romania",      isFAA: false, timezone: "Europe/Bucharest" },
  KBP: { name: "Boryspil International Airport",      city: "Kyiv",          state: "UA", lat: 50.3450,  lng: 30.8947,   icao: "UKBB", country: "Ukraine",      isFAA: false, timezone: "Europe/Kiev" },

  // ── Middle East ───────────────────────────────────────────────────────────
  DXB: { name: "Dubai International Airport",         city: "Dubai",         state: "AE", lat: 25.2532,  lng: 55.3657,   icao: "OMDB", country: "UAE",          isFAA: false, timezone: "Asia/Dubai" },
  AUH: { name: "Abu Dhabi International Airport",     city: "Abu Dhabi",     state: "AE", lat: 24.4330,  lng: 54.6511,   icao: "OMAA", country: "UAE",          isFAA: false, timezone: "Asia/Dubai" },
  DOH: { name: "Hamad International Airport",         city: "Doha",          state: "QA", lat: 25.2731,  lng: 51.6081,   icao: "OTHH", country: "Qatar",        isFAA: false, timezone: "Asia/Qatar" },
  BAH: { name: "Bahrain International Airport",       city: "Manama",        state: "BH", lat: 26.2708,  lng: 50.6336,   icao: "OBBI", country: "Bahrain",      isFAA: false, timezone: "Asia/Bahrain" },
  KWI: { name: "Kuwait International Airport",        city: "Kuwait City",   state: "KW", lat: 29.2266,  lng: 47.9689,   icao: "OKBK", country: "Kuwait",       isFAA: false, timezone: "Asia/Kuwait" },
  AMM: { name: "Queen Alia International Airport",    city: "Amman",         state: "JO", lat: 31.7226,  lng: 35.9932,   icao: "OJAI", country: "Jordan",       isFAA: false, timezone: "Asia/Amman" },
  BEY: { name: "Rafic Hariri International Airport",  city: "Beirut",        state: "LB", lat: 33.8209,  lng: 35.4886,   icao: "OLBA", country: "Lebanon",      isFAA: false, timezone: "Asia/Beirut" },
  TLV: { name: "Ben Gurion International Airport",    city: "Tel Aviv",      state: "IL", lat: 32.0114,  lng: 34.8867,   icao: "LLBG", country: "Israel",       isFAA: false, timezone: "Asia/Jerusalem" },
  RUH: { name: "King Khalid International Airport",   city: "Riyadh",        state: "SA", lat: 24.9576,  lng: 46.6988,   icao: "OERK", country: "Saudi Arabia", isFAA: false, timezone: "Asia/Riyadh" },
  JED: { name: "King Abdulaziz International Airport",city: "Jeddah",        state: "SA", lat: 21.6796,  lng: 39.1565,   icao: "OEJN", country: "Saudi Arabia", isFAA: false, timezone: "Asia/Riyadh" },
  MCT: { name: "Muscat International Airport",        city: "Muscat",        state: "OM", lat: 23.5933,  lng: 58.2844,   icao: "OOMS", country: "Oman",         isFAA: false, timezone: "Asia/Muscat" },
  CAI: { name: "Cairo International Airport",         city: "Cairo",         state: "EG", lat: 30.1219,  lng: 31.4056,   icao: "HECA", country: "Egypt",        isFAA: false, timezone: "Africa/Cairo" },

  // ── Asia-Pacific ──────────────────────────────────────────────────────────
  NRT: { name: "Narita International Airport",        city: "Tokyo",         state: "JP", lat: 35.7647,  lng: 140.3864,  icao: "RJAA", country: "Japan",        isFAA: false, timezone: "Asia/Tokyo" },
  HND: { name: "Tokyo Haneda Airport",                city: "Tokyo",         state: "JP", lat: 35.5494,  lng: 139.7798,  icao: "RJTT", country: "Japan",        isFAA: false, timezone: "Asia/Tokyo" },
  KIX: { name: "Kansai International Airport",        city: "Osaka",         state: "JP", lat: 34.4347,  lng: 135.2440,  icao: "RJBB", country: "Japan",        isFAA: false, timezone: "Asia/Tokyo" },
  ICN: { name: "Incheon International Airport",       city: "Seoul",         state: "KR", lat: 37.4691,  lng: 126.4507,  icao: "RKSI", country: "South Korea",  isFAA: false, timezone: "Asia/Seoul" },
  GMP: { name: "Gimpo International Airport",         city: "Seoul",         state: "KR", lat: 37.5583,  lng: 126.7906,  icao: "RKSS", country: "South Korea",  isFAA: false, timezone: "Asia/Seoul" },
  PEK: { name: "Beijing Capital International Airport",city: "Beijing",      state: "CN", lat: 40.0799,  lng: 116.6031,  icao: "ZBAA", country: "China",        isFAA: false, timezone: "Asia/Shanghai" },
  PKX: { name: "Beijing Daxing International Airport",city: "Beijing",       state: "CN", lat: 39.5098,  lng: 116.4105,  icao: "ZBAD", country: "China",        isFAA: false, timezone: "Asia/Shanghai" },
  PVG: { name: "Shanghai Pudong International Airport",city: "Shanghai",     state: "CN", lat: 31.1434,  lng: 121.8052,  icao: "ZSPD", country: "China",        isFAA: false, timezone: "Asia/Shanghai" },
  SHA: { name: "Shanghai Hongqiao International",     city: "Shanghai",      state: "CN", lat: 31.1979,  lng: 121.3363,  icao: "ZSSS", country: "China",        isFAA: false, timezone: "Asia/Shanghai" },
  CAN: { name: "Guangzhou Baiyun International",      city: "Guangzhou",     state: "CN", lat: 23.3925,  lng: 113.2990,  icao: "ZGGG", country: "China",        isFAA: false, timezone: "Asia/Shanghai" },
  HKG: { name: "Hong Kong International Airport",     city: "Hong Kong",     state: "HK", lat: 22.3080,  lng: 113.9185,  icao: "VHHH", country: "Hong Kong",    isFAA: false, timezone: "Asia/Hong_Kong" },
  TPE: { name: "Taiwan Taoyuan International Airport",city: "Taipei",        state: "TW", lat: 25.0777,  lng: 121.2330,  icao: "RCTP", country: "Taiwan",       isFAA: false, timezone: "Asia/Taipei" },
  SIN: { name: "Singapore Changi Airport",            city: "Singapore",     state: "SG", lat: 1.3644,   lng: 103.9915,  icao: "WSSS", country: "Singapore",    isFAA: false, timezone: "Asia/Singapore" },
  KUL: { name: "Kuala Lumpur International Airport",  city: "Kuala Lumpur",  state: "MY", lat: 2.7456,   lng: 101.7072,  icao: "WMKK", country: "Malaysia",     isFAA: false, timezone: "Asia/Kuala_Lumpur" },
  BKK: { name: "Suvarnabhumi Airport",                city: "Bangkok",       state: "TH", lat: 13.6811,  lng: 100.7472,  icao: "VTBS", country: "Thailand",     isFAA: false, timezone: "Asia/Bangkok" },
  DMK: { name: "Don Mueang International Airport",    city: "Bangkok",       state: "TH", lat: 13.9126,  lng: 100.6067,  icao: "VTBD", country: "Thailand",     isFAA: false, timezone: "Asia/Bangkok" },
  CGK: { name: "Soekarno-Hatta International Airport",city: "Jakarta",       state: "ID", lat: -6.1256,  lng: 106.6559,  icao: "WIII", country: "Indonesia",    isFAA: false, timezone: "Asia/Jakarta" },
  HAN: { name: "Noi Bai International Airport",       city: "Hanoi",         state: "VN", lat: 21.2212,  lng: 105.8072,  icao: "VVNB", country: "Vietnam",      isFAA: false, timezone: "Asia/Ho_Chi_Minh" },
  SGN: { name: "Tan Son Nhat International Airport",  city: "Ho Chi Minh City", state: "VN", lat: 10.8188, lng: 106.6520, icao: "VVTS", country: "Vietnam",     isFAA: false, timezone: "Asia/Ho_Chi_Minh" },
  MNL: { name: "Ninoy Aquino International Airport",  city: "Manila",        state: "PH", lat: 14.5086,  lng: 121.0197,  icao: "RPLL", country: "Philippines",  isFAA: false, timezone: "Asia/Manila" },
  DEL: { name: "Indira Gandhi International Airport", city: "New Delhi",     state: "IN", lat: 28.5665,  lng: 77.1031,   icao: "VIDP", country: "India",        isFAA: false, timezone: "Asia/Kolkata" },
  BOM: { name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai",  state: "IN", lat: 19.0896,  lng: 72.8656,   icao: "VABB", country: "India",        isFAA: false, timezone: "Asia/Kolkata" },
  BLR: { name: "Kempegowda International Airport",    city: "Bengaluru",     state: "IN", lat: 13.1986,  lng: 77.7066,   icao: "VOBL", country: "India",        isFAA: false, timezone: "Asia/Kolkata" },
  SYD: { name: "Sydney Kingsford Smith Airport",      city: "Sydney",        state: "AU", lat: -33.9399, lng: 151.1753,  icao: "YSSY", country: "Australia",    isFAA: false, timezone: "Australia/Sydney" },
  MEL: { name: "Melbourne Airport",                   city: "Melbourne",     state: "AU", lat: -37.6690, lng: 144.8410,  icao: "YMML", country: "Australia",    isFAA: false, timezone: "Australia/Melbourne" },
  BNE: { name: "Brisbane Airport",                    city: "Brisbane",      state: "AU", lat: -27.3842, lng: 153.1175,  icao: "YBBN", country: "Australia",    isFAA: false, timezone: "Australia/Brisbane" },
  PER: { name: "Perth Airport",                       city: "Perth",         state: "AU", lat: -31.9403, lng: 115.9669,  icao: "YPPH", country: "Australia",    isFAA: false, timezone: "Australia/Perth" },
  AKL: { name: "Auckland Airport",                    city: "Auckland",      state: "NZ", lat: -37.0082, lng: 174.7850,  icao: "NZAA", country: "New Zealand",  isFAA: false, timezone: "Pacific/Auckland" },

  // ── Africa ────────────────────────────────────────────────────────────────
  JNB: { name: "O.R. Tambo International Airport",    city: "Johannesburg",  state: "ZA", lat: -26.1392, lng: 28.2460,   icao: "FAOR", country: "South Africa", isFAA: false, timezone: "Africa/Johannesburg" },
  CPT: { name: "Cape Town International Airport",     city: "Cape Town",     state: "ZA", lat: -33.9648, lng: 18.6017,   icao: "FACT", country: "South Africa", isFAA: false, timezone: "Africa/Johannesburg" },
  NBO: { name: "Jomo Kenyatta International Airport", city: "Nairobi",       state: "KE", lat: -1.3192,  lng: 36.9275,   icao: "HKJK", country: "Kenya",        isFAA: false, timezone: "Africa/Nairobi" },
  ADD: { name: "Bole International Airport",          city: "Addis Ababa",   state: "ET", lat: 8.9779,   lng: 38.7993,   icao: "HAAB", country: "Ethiopia",     isFAA: false, timezone: "Africa/Addis_Ababa" },
  CMN: { name: "Mohammed V International Airport",    city: "Casablanca",    state: "MA", lat: 33.3675,  lng: -7.5900,   icao: "GMMN", country: "Morocco",      isFAA: false, timezone: "Africa/Casablanca" },
  ACC: { name: "Kotoka International Airport",        city: "Accra",         state: "GH", lat: 5.6052,   lng: -0.1668,   icao: "DGAA", country: "Ghana",        isFAA: false, timezone: "Africa/Accra" },
  LOS: { name: "Murtala Muhammed International",      city: "Lagos",         state: "NG", lat: 6.5774,   lng: 3.3212,    icao: "DNMM", country: "Nigeria",      isFAA: false, timezone: "Africa/Lagos" },
  TUN: { name: "Tunis-Carthage International Airport",city: "Tunis",         state: "TN", lat: 36.8510,  lng: 10.2272,   icao: "DTTA", country: "Tunisia",      isFAA: false, timezone: "Africa/Tunis" },
};

export const DEFAULT_AIRPORTS = ["MIA", "JFK", "EZE", "GCM"];
