export const COUNTRY_FLAGS: Record<string, string> = {
  Argentina:          "🇦🇷",
  Brazil:             "🇧🇷",
  Chile:              "🇨🇱",
  Colombia:           "🇨🇴",
  Peru:               "🇵🇪",
  Uruguay:            "🇺🇾",
  Bolivia:            "🇧🇴",
  Ecuador:            "🇪🇨",
  Panama:             "🇵🇦",
  Mexico:             "🇲🇽",
  Cuba:               "🇨🇺",
  "Dominican Republic": "🇩🇴",
  "Puerto Rico":      "🇵🇷",
  Bahamas:            "🇧🇸",
  Jamaica:            "🇯🇲",
  Barbados:           "🇧🇧",
  Curaçao:            "🇨🇼",
  Aruba:              "🇦🇼",
  Antigua:            "🇦🇬",
  "Trinidad & Tobago":"🇹🇹",
  "Costa Rica":       "🇨🇷",
  Guatemala:          "🇬🇹",
  "El Salvador":      "🇸🇻",
  "Cayman Islands":   "🇰🇾",
  "United Kingdom":   "🇬🇧",
  France:             "🇫🇷",
  Spain:              "🇪🇸",
  Italy:              "🇮🇹",
  Germany:            "🇩🇪",
  Netherlands:        "🇳🇱",
  Portugal:           "🇵🇹",
  Switzerland:        "🇨🇭",
  Austria:            "🇦🇹",
  Belgium:            "🇧🇪",
  Greece:             "🇬🇷",
  Turkey:             "🇹🇷",
  Norway:             "🇳🇴",
  Sweden:             "🇸🇪",
  Denmark:            "🇩🇰",
  Finland:            "🇫🇮",
  Poland:             "🇵🇱",
  Japan:              "🇯🇵",
  China:              "🇨🇳",
  "South Korea":      "🇰🇷",
  India:              "🇮🇳",
  Thailand:           "🇹🇭",
  Singapore:          "🇸🇬",
  Australia:          "🇦🇺",
  "New Zealand":      "🇳🇿",
  Canada:             "🇨🇦",
  USA:                "🇺🇸",
};

export function countryFlag(country: string): string {
  return COUNTRY_FLAGS[country] ?? "🌍";
}
